# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20161201_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='pmbnum',
            field=models.FloatField(verbose_name='\u4f9b\u5e94\u5546\u624b\u673a'),
        ),
    ]
