# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20161201_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deptinfo',
            options={'verbose_name': '/Meta/\u90e8\u95e8', 'verbose_name_plural': '/Meta/\u90e8\u95e8'},
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='dept_owneremail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90e8\u95e8\u8d1f\u8d23\u4eba\u90ae\u7bb1\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='dept_ownerid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u90e8\u95e8\u8d1f\u8d23\u4eba\u5de5\u53f7'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='dept_ownername',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u90e8\u95e8\u8d1f\u8d23\u4eba\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='dept_status',
            field=models.CharField(choices=[('T', '\u6b63\u5e38'), ('F', '\u5f02\u5e38')], default='T', help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, verbose_name='\u90e8\u95e8\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='memo',
            field=models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
