# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20161201_1935'),
    ]

    operations = [
    ]
