# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20161201_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptinfo',
            name='dept_owneremail',
            field=models.EmailField(blank=True, help_text='\u5fc5\u987b\u552f\u4e00', max_length=254, null=True, unique=True, verbose_name='\u90e8\u95e8\u8d1f\u8d23\u4eba\u90ae\u7bb1\u5730\u5740'),
        ),
    ]
