# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20161201_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystemversion',
            options={'verbose_name': '/Meta/\u64cd\u4f5c\u7cfb\u7edf\u53d1\u884c\u7248', 'verbose_name_plural': '/Meta/\u64cd\u4f5c\u7cfb\u7edf\u53d1\u884c\u7248'},
        ),
        migrations.AlterField(
            model_name='operatingsystemversion',
            name='memo',
            field=models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='operatingsystemversion',
            name='os_version',
            field=models.CharField(help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, unique=True, verbose_name='\u7248\u672c\u53f7'),
        ),
        migrations.AlterField(
            model_name='operatingsystemversion',
            name='osname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OperatingSystem_Version', to='cmdb.OperatingSystem', verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
    ]
