# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20161201_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystemversion',
            options={'verbose_name': '/Meta/\u64cd\u4f5c\u7cfb\u7edf\u53d1\u884c\u7248\u7248\u672c\u53f7', 'verbose_name_plural': '/Meta/\u64cd\u4f5c\u7cfb\u7edf\u53d1\u884c\u7248\u7248\u672c\u53f7'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': '/Meta/\u4f9b\u5e94\u5546', 'verbose_name_plural': '/Meta/\u4f9b\u5e94\u5546'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='pcname',
            field=models.CharField(help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, unique=True, verbose_name='\u4f9b\u5e94\u5546\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pmbnum',
            field=models.CharField(help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, unique=True, verbose_name='\u4f9b\u5e94\u5546\u624b\u673a'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='poname',
            field=models.CharField(help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, unique=True, verbose_name='\u4f9b\u5e94\u5546\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ptype',
            field=models.CharField(choices=[('1', '\u516c\u6709\u4e91'), ('2', '\u8d1f\u8f7d\u5747\u8861'), ('3', '\u5e26\u5bbd&\u901a\u4fe1'), ('4', '\u670d\u52a1\u5668&\u4e3b\u673a'), ('5', '\u4e13\u7ebf'), ('6', '\u4ea4\u6362\u673a'), ('7', '\u9632\u706b\u5899'), ('8', 'IDC'), ('9', '\u5b58\u50a8'), ('10', '\u5b89\u5168'), ('11', '\u7cfb\u7edf\u96c6\u6210&OA')], default='11', help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, verbose_name='\u4f9b\u5e94\u5546\u7c7b\u522b'),
        ),
    ]
