# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_auto_20161201_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerissue',
            name='piname',
        ),
        migrations.DeleteModel(
            name='ProviderIssue',
        ),
    ]
