# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20161201_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pistype', models.CharField(choices=[('1', 'NOC\u5e73\u53f0'), ('2', '\u76d1\u63a7\u544a\u8b66\u5e73\u53f0'), ('3', '\u811a\u672c&\u81ea\u52a8\u53d1\u73b0'), ('4', '\u4eba\u5de5\u53d1\u73b0'), ('5', '\u5176\u4ed6\u4e0a\u62a5\u6e20\u9053')], default='5', max_length=255, verbose_name='\u95ee\u9898\u6765\u6e90\u6e20\u9053')),
                ('pistartdate', models.DateTimeField(default=django.utils.timezone.now, max_length=255, verbose_name='\u95ee\u9898\u53d1\u751f\u65f6\u95f4,\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9')),
                ('pitype', models.CharField(choices=[('1', '\u670d\u52a1\u6545\u969c'), ('2', '\u786c\u4ef6\u6545\u969c'), ('3', '\u8f6f\u4ef6\u6545\u969c'), ('4', '\u5176\u4ed6\u6545\u969c')], default='2', max_length=255, verbose_name='\u6545\u969c\u5206\u7c7b')),
                ('piremark', models.TextField(max_length=1000, verbose_name='\u95ee\u9898\u63cf\u8ff0')),
                ('pisolution', models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u89e3\u51b3\u65b9\u6848')),
                ('piprogress', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u89e3\u51b3\u8fdb\u5ea6')),
                ('pienddate', models.DateTimeField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u95ee\u9898\u89e3\u51b3\u65f6\u95f4')),
                ('pimemo', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '/Meta/\u4f9b\u5e94\u5546\u95ee\u9898',
                'verbose_name_plural': '/Meta/\u4f9b\u5e94\u5546\u95ee\u9898',
            },
        ),
        migrations.AlterField(
            model_name='provider',
            name='ptype',
            field=models.CharField(choices=[('1', '\u516c\u6709\u4e91'), ('2', '\u8d1f\u8f7d\u5747\u8861'), ('3', '\u5e26\u5bbd&\u4e13\u7ebf'), ('4', '\u670d\u52a1\u5668&\u4e3b\u673a'), ('5', '\u4ea4\u6362\u673a'), ('6', 'IDC'), ('7', '\u5b58\u50a8'), ('8', '\u5b89\u5168&\u9632\u706b\u5899'), ('9', '\u7cfb\u7edf\u96c6\u6210&OA')], default='9', help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, verbose_name='\u4f9b\u5e94\u5546\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='providerissue',
            name='piname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Provider_Name', to='cmdb.Provider', verbose_name='\u4f9b\u5e94\u5546'),
        ),
    ]
