# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20161201_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerissue',
            name='pistartdate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u95ee\u9898\u53d1\u751f\u65f6\u95f4'),
        ),
    ]
