# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_auto_20161201_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerissue',
            name='pitype',
            field=models.CharField(choices=[('1', '\u786c\u4ef6\u6545\u969c'), ('2', '\u8f6f\u4ef6\u6545\u969c'), ('3', '\u670d\u52a1\u6545\u969c'), ('4', '\u5176\u4ed6\u6545\u969c')], default='1', max_length=255, verbose_name='\u6545\u969c\u5206\u7c7b'),
        ),
    ]
