# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0021_auto_20161201_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingsystemversion',
            old_name='osname',
            new_name='os_name',
        ),
    ]
