# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_auto_20161201_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystemversion',
            options={'verbose_name': '/Meta/\u64cd\u4f5c\u7cfb\u7edf', 'verbose_name_plural': '/Meta/\u64cd\u4f5c\u7cfb\u7edf'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='pcooperate',
            field=models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u4f9b\u5e94\u5546\u7d27\u5bc6\u5ea6'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pmemo',
            field=models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ptelnum',
            field=models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u4f9b\u5e94\u5546\u5ea7\u673a'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ptype',
            field=models.CharField(choices=[('1', '\u516c\u6709\u4e91'), ('2', '\u8d1f\u8f7d\u5747\u8861'), ('3', '\u5e26\u5bbd&\u4e13\u7ebf'), ('4', '\u670d\u52a1\u5668&\u4e3b\u673a'), ('5', '\u4ea4\u6362\u673a'), ('6', 'IDC'), ('7', '\u5b58\u50a8'), ('8', '\u5b89\u5168&\u9632\u706b\u5899'), ('9', '\u7cfb\u7edf\u96c6\u6210&OA')], default='9', max_length=255, verbose_name='\u4f9b\u5e94\u5546\u7c7b\u522b'),
        ),
    ]
