# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0023_auto_20161201_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='pcooperate',
            new_name='cooperate',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='pmbnum',
            new_name='mb_num',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='pmemo',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='pcname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='poname',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='ptelnum',
            new_name='tel_num',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='ptype',
            new_name='type',
        ),
    ]
