# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0024_auto_20161201_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerissue',
            old_name='pimemo',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='providerissue',
            old_name='piname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='providerissue',
            old_name='piremark',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='providerissue',
            old_name='pisolution',
            new_name='solution',
        ),
        migrations.RenameField(
            model_name='providerissue',
            old_name='pistartdate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='providerissue',
            old_name='pistype',
            new_name='stype',
        ),
        migrations.RenameField(
            model_name='providerissue',
            old_name='pitype',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='providerissue',
            name='pienddate',
        ),
        migrations.RemoveField(
            model_name='providerissue',
            name='piprogress',
        ),
        migrations.AddField(
            model_name='providerissue',
            name='end_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='\u95ee\u9898\u89e3\u51b3\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='providerissue',
            name='progress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u89e3\u51b3\u8fdb\u5ea6'),
        ),
    ]
