# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0026_auto_20161201_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrartType',
        ),
    ]
