# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0027_delete_prarttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, unique=True, verbose_name='\u914d\u4ef6\u7c7b\u578b')),
                ('memo', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '/Meta/\u914d\u4ef6\u7c7b\u578b',
                'verbose_name_plural': '/Meta/\u914d\u4ef6\u7c7b\u578b',
            },
        ),
    ]
