# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0034_brandmodel_modelconf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconf',
            name='brand_model',
        ),
        migrations.AddField(
            model_name='modelconf',
            name='brand_model',
            field=models.ManyToManyField(related_name='model', to='cmdb.BrandModel', verbose_name='\u54c1\u724c/\u578b\u53f7'),
        ),
    ]
