# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0042_auto_20161204_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=255, verbose_name='\u4ea7\u54c1'),
        ),
    ]
