# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0043_auto_20161204_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u53d1\u8d77\u65f6\u95f4')),
                ('hostname', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='\u4e3b\u673aIP\u5730\u5740')),
                ('recover_type', models.CharField(choices=[('1', 'EWF'), ('2', '\u5176\u4ed6')], default='1', max_length=255, verbose_name='\u56de\u6536\u4eba')),
                ('status', models.CharField(choices=[('1', '\u5b8c\u6210'), ('2', '\u5f02\u5e38')], default='1', max_length=255, verbose_name='\u56de\u6536\u7ed3\u679c')),
                ('applicant', models.CharField(max_length=255, verbose_name='\u53d1\u8d77\u4eba')),
                ('memo', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('end_date', models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='\u95ee\u9898\u89e3\u51b3\u65f6\u95f4')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='cmdb.Dept', verbose_name='\u6838\u7b97\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '/Meta/\u4e3b\u673a\u56de\u6536',
                'verbose_name_plural': '/Meta/\u4e3b\u673a\u56de\u6536',
            },
        ),
    ]
