# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0047_auto_20161205_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalerror',
            name='status',
            field=models.CharField(choices=[('1', '\u5df2\u4fee\u590d'), ('2', '\u672a\u4fee\u590d')], default='2', max_length=255, verbose_name='\u4fee\u590d\u72b6\u6001'),
        ),
    ]
