# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0048_auto_20161205_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '\u6b63\u5e38'), ('2', '\u4e0b\u7ebf')], default='2', max_length=255, verbose_name='\u9879\u76ee\u72b6\u6001')),
                ('memo', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('project', models.CharField(max_length=255, unique=True, verbose_name='\u9879\u76ee')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_project', to='cmdb.Dept', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '/Meta/\u9879\u76ee',
                'verbose_name_plural': '/Meta/\u9879\u76ee',
            },
        ),
    ]
