# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0049_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '\u5728\u804c'), ('2', '\u5f02\u5e38')], default='1', max_length=255, verbose_name='\u5728\u804c\u72b6\u6001')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='\u5de5\u53f7')),
                ('cnname', models.CharField(max_length=255, verbose_name='\u4e2d\u6587\u59d3\u540d')),
                ('name', models.CharField(max_length=255, verbose_name='\u82f1\u6587\u59d3\u540d')),
                ('mail', models.EmailField(blank=True, help_text='\u5fc5\u987b\u552f\u4e00', max_length=254, null=True, unique=True, verbose_name='\u90ae\u7bb1')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('memo', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_staff', to='cmdb.Dept', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '/Meta/\u4eba\u5458\u4fe1\u606f',
                'verbose_name_plural': '/Meta/\u4eba\u5458\u4fe1\u606f',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', '\u6b63\u5e38'), ('2', '\u4e0b\u7ebf')], default='1', max_length=255, verbose_name='\u9879\u76ee\u72b6\u6001'),
        ),
    ]
