# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0050_auto_20161205_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u673a\u623f')),
                ('remark', models.TextField(max_length=1000, verbose_name='\u63cf\u8ff0')),
                ('address', models.TextField(max_length=1000, verbose_name='\u5730\u5740')),
                ('contact', models.TextField(max_length=1000, verbose_name='\u8054\u7cfb\u4eba')),
                ('mb_num', models.CharField(help_text='\u5fc5\u987b\u552f\u4e00&\u4e0d\u80fd\u4e3a\u7a7a', max_length=255, unique=True, verbose_name='\u4f9b\u5e94\u5546\u624b\u673a')),
                ('tel_num', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u4f9b\u5e94\u5546\u5ea7\u673a')),
                ('code', models.TextField(max_length=1000, verbose_name='\u673a\u623f\u7f16\u7801')),
                ('memo', models.TextField(default='\u5bbd\u5e26\u53ca\u7c7b\u578b:\n \u5176\u4ed6:\n ', max_length=255, verbose_name='\u5907\u6ce8')),
            ],
        ),
    ]
