# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0051_idc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '/Meta/\u673a\u623f', 'verbose_name_plural': '/Meta/\u673a\u623f'},
        ),
        migrations.AlterField(
            model_name='idc',
            name='remark',
            field=models.CharField(max_length=1000, verbose_name='\u63cf\u8ff0'),
        ),
    ]
