# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0053_auto_20161206_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='code',
            field=models.CharField(max_length=1000, verbose_name='\u673a\u623f\u7f16\u7801'),
        ),
    ]
