# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0054_auto_20161206_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='memo',
            field=models.TextField(default='\u5bbd\u5e26\u53ca\u7c7b\u578b:\n\u5176\u4ed6:\n ', max_length=255, verbose_name='\u5907\u6ce8'),
        ),
    ]
