# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0058_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliver',
            name='applicant_cname',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='applicant_dept',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='applicant_no',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='modelconf',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='use_dept',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='use_deptowner',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='use_names',
        ),
        migrations.DeleteModel(
            name='Deliver',
        ),
    ]
