# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0065_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='actual_date',
            field=models.DateTimeField(blank=True, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, null=True, verbose_name='\u5b9e\u9645\u4ea4\u4ed8\u65f6\u95f4'),
        ),
    ]
