# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0067_auto_20161206_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='conf_details',
        ),
        migrations.RemoveField(
            model_name='contractconfig',
            name='type',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ContractConfig',
        ),
    ]
