# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0068_auto_20161206_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparty', models.CharField(max_length=255, verbose_name='\u7532\u65b9')),
                ('bparty', models.CharField(max_length=255, verbose_name='\u4e59\u65b9')),
                ('project', models.CharField(max_length=255, verbose_name='\u9879\u76ee')),
                ('contract_amount', models.TextField(default='\u5408\u540c\u91d1\u989d:\n\u670d\u52a1\u5668\u91d1\u989d:\n\u5176\u4ed6\u91d1\u989d:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5408\u540c\u91d1\u989d')),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u5230\u8d27\u65f6\u95f4')),
                ('receipt_place', models.CharField(max_length=255, verbose_name='\u6536\u8d27\u5730\u70b9')),
                ('advance_payment', models.TextField(default='\u9884\u4ed8\u6b3e:\n\u4ed8\u6b3e\u65e5\u671f:\n\u6bd4\u4f8b:\n\u5176\u4ed6:', max_length=255, verbose_name='\u9884\u4ed8\u6b3e')),
                ('final_payment', models.TextField(default='\u5c3e\u6b3e:\n\u4ed8\u6b3e\u65e5\u671f:\n\u6bd4\u4f8b:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5c3e\u6b3e')),
                ('signing_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u7b7e\u8ba2\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '/Meta/\u5408\u540c',
                'verbose_name_plural': '/Meta/\u5408\u540c',
            },
        ),
        migrations.CreateModel(
            name='ContractConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField(max_length=255, verbose_name='\u914d\u7f6e\u8be6\u60c5')),
                ('count', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('cost', models.IntegerField(verbose_name='\u5355\u4ef7')),
                ('cost_total', models.IntegerField(verbose_name='\u5355\u9879\u603b\u4ef7')),
                ('contract_cost', models.IntegerField(verbose_name='\u5408\u540c\u603b\u4ef7')),
                ('memo', models.TextField(default='\u9879\u76ee:\n\u603b\u4ef7:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5907\u6ce8')),
                ('brandmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandmodel', to='cmdb.BrandModel', verbose_name='\u54c1\u724c/\u89c4\u683c')),
                ('prartyype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prartyype', to='cmdb.PrartType', verbose_name='\u914d\u7f6e\u7c7b\u522b')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='conf_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractconfig', to='cmdb.ContractConfig', verbose_name='\u914d\u7f6e\u8be6\u60c5'),
        ),
    ]
