# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0069_auto_20161206_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='memo',
            field=models.TextField(default='\u9879\u76ee:\n\u603b\u4ef7:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5907\u6ce8'),
        ),
    ]
