# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0070_contract_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='bparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bparty', to='cmdb.Provider', verbose_name='\u4e59\u65b9'),
        ),
    ]
