# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0074_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('1', '\u7b49\u5f85\u4f9b\u5e94\u5546\u53d1\u9001\u5408\u540c\u7535\u5b50\u7248'), ('2', '\u6cd5\u52a1\u5ba1\u6279\u4e2d'), ('3', '\u5feb\u9012\u76d6\u7ae0\u7eb8\u8d28\u5408\u540c\u5236\u4f9b\u5e94\u5546'), ('4', '\u4f9b\u5e94\u5546\u5f55\u5165'), ('5', '\u4f9b\u5e94\u5546\u5165\u5e93'), ('6', '\u4f9b\u5e94\u5546\u4e0b\u5355')], default='6', max_length=255, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('1', '\u516c\u6709\u4e91'), ('2', '\u8d1f\u8f7d\u5747\u8861'), ('3', '\u5e26\u5bbd&\u4e13\u7ebf'), ('4', '\u670d\u52a1\u5668&\u4e3b\u673a'), ('5', '\u4ea4\u6362\u673a'), ('6', 'IDC'), ('7', '\u5b58\u50a8'), ('8', '\u5b89\u5168&\u9632\u706b\u5899&\u8bc1\u4e66'), ('9', '\u7cfb\u7edf\u96c6\u6210&OA')], default='9', max_length=255, verbose_name='\u4f9b\u5e94\u5546\u7c7b\u522b'),
        ),
    ]
