# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0075_auto_20161207_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommInfo',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='bparty',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='conf_details',
        ),
        migrations.RemoveField(
            model_name='contractconfig',
            name='brandmodel',
        ),
        migrations.RemoveField(
            model_name='contractconfig',
            name='prartyype',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ContractConfig',
        ),
    ]
