# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0078_auto_20161207_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '\u7b49\u5f85\u4f9b\u5e94\u5546\u53d1\u9001\u5408\u540c\u7535\u5b50\u7248'), ('2', '\u6cd5\u52a1\u5ba1\u6279\u4e2d'), ('3', '\u5feb\u9012\u76d6\u7ae0\u7eb8\u8d28\u5408\u540c\u5236\u4f9b\u5e94\u5546'), ('4', '\u4f9b\u5e94\u5546\u5f55\u5165'), ('5', '\u4f9b\u5e94\u5546\u5165\u5e93'), ('6', '\u4f9b\u5e94\u5546\u4e0b\u5355')], default='6', max_length=255, verbose_name='\u72b6\u6001')),
                ('sn', models.IntegerField(help_text='\u8d22\u52a1\u7f16\u53f7', verbose_name='\u8d22\u52a1\u7f16\u53f7')),
                ('aparty', models.CharField(max_length=255, verbose_name='\u7532\u65b9')),
                ('project', models.CharField(max_length=255, verbose_name='\u9879\u76ee')),
                ('contract_amount', models.TextField(default='\u5408\u540c\u91d1\u989d:\n\u670d\u52a1\u5668\u91d1\u989d:\n\u5176\u4ed6\u91d1\u989d:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5408\u540c\u91d1\u989d')),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u5230\u8d27\u65f6\u95f4')),
                ('receipt_place', models.CharField(max_length=255, verbose_name='\u6536\u8d27\u5730\u70b9')),
                ('advance_payment', models.TextField(default='\u9884\u4ed8\u6b3e:\n\u4ed8\u6b3e\u65e5\u671f:\n\u6bd4\u4f8b:\n\u5176\u4ed6:', max_length=255, verbose_name='\u9884\u4ed8\u6b3e')),
                ('final_payment', models.TextField(default='\u5c3e\u6b3e:\n\u4ed8\u6b3e\u65e5\u671f:\n\u6bd4\u4f8b:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5c3e\u6b3e')),
                ('signing_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u7b7e\u8ba2\u65f6\u95f4')),
                ('memo', models.TextField(default='\u9879\u76ee:\n\u603b\u4ef7:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5907\u6ce8')),
                ('bparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bparty', to='cmdb.Provider', verbose_name='\u4e59\u65b9')),
            ],
            options={
                'verbose_name': '/Meta/\u5408\u540c',
                'verbose_name_plural': '/Meta/\u5408\u540c',
            },
        ),
        migrations.CreateModel(
            name='ContractConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField(max_length=255, verbose_name='\u914d\u7f6e\u8be6\u60c5')),
                ('count', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('cost', models.IntegerField(verbose_name='\u5355\u4ef7')),
                ('cost_total', models.IntegerField(verbose_name='\u5355\u9879\u603b\u4ef7')),
                ('contract_cost', models.IntegerField(verbose_name='\u5408\u540c\u603b\u4ef7')),
                ('memo', models.TextField(default='\u9879\u76ee:\n\u603b\u4ef7:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5907\u6ce8')),
                ('brandmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandmodel', to='cmdb.BrandModel', verbose_name='\u54c1\u724c/\u89c4\u683c')),
            ],
            options={
                'verbose_name': '/Meta/\u5408\u540c\u914d\u7f6e',
                'verbose_name_plural': '/Meta/\u5408\u540c\u914d\u7f6e',
            },
        ),
        migrations.AddField(
            model_name='prarttype',
            name='provider',
            field=models.ManyToManyField(related_name='provider', to='cmdb.Provider', verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AddField(
            model_name='contractconfig',
            name='prartyype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prartyype', to='cmdb.PrartType', verbose_name='\u914d\u7f6e\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='contract',
            name='conf_details',
            field=models.ManyToManyField(related_name='contractconfig', to='cmdb.ContractConfig', verbose_name='\u914d\u7f6e\u8be6\u60c5'),
        ),
    ]
