# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0082_auto_20161207_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '\u7b49\u5f85\u4f9b\u5e94\u5546\u53d1\u9001\u5408\u540c\u7535\u5b50\u7248'), ('2', '\u6cd5\u52a1\u5ba1\u6279\u4e2d'), ('3', '\u5feb\u9012\u76d6\u7ae0\u7eb8\u8d28\u5408\u540c\u5236\u4f9b\u5e94\u5546'), ('4', '\u4f9b\u5e94\u5546\u5f55\u5165'), ('5', '\u4f9b\u5e94\u5546\u5165\u5e93'), ('6', '\u4f9b\u5e94\u5546\u4e0b\u5355')], default='6', max_length=255, verbose_name='\u72b6\u6001')),
                ('sn', models.IntegerField(help_text='\u8d22\u52a1\u7f16\u53f7', verbose_name='\u8d22\u52a1\u7f16\u53f7')),
                ('aparty', models.CharField(max_length=255, verbose_name='\u7532\u65b9')),
                ('project', models.CharField(max_length=255, verbose_name='\u9879\u76ee')),
                ('contract_amount', models.TextField(default='\u5408\u540c\u91d1\u989d:\n\u670d\u52a1\u5668\u91d1\u989d:\n\u5176\u4ed6\u91d1\u989d:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5408\u540c\u91d1\u989d')),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u5230\u8d27\u65f6\u95f4')),
                ('receipt_place', models.CharField(max_length=255, verbose_name='\u6536\u8d27\u5730\u70b9')),
                ('advance_payment', models.TextField(default='\u9884\u4ed8\u6b3e:\n\u4ed8\u6b3e\u65e5\u671f:\n\u6bd4\u4f8b:\n\u5176\u4ed6:', max_length=255, verbose_name='\u9884\u4ed8\u6b3e')),
                ('final_payment', models.TextField(default='\u5c3e\u6b3e:\n\u4ed8\u6b3e\u65e5\u671f:\n\u6bd4\u4f8b:\n\u5176\u4ed6:', max_length=255, verbose_name='\u5c3e\u6b3e')),
                ('signing_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u7b7e\u8ba2\u65f6\u95f4')),
                ('memo', models.TextField(default='\u6bd4\u4ef7\u65f6\u95f4:\n\u6bd4\u4ef7\u8fc7\u7a0b:\n\u51b3\u7b56\u65f6\u95f4:\n\u5b89\u88c5\u8c03\u8bd5\u65f6\u95f4:\n\u9996\u6b21\u4ed8\u6b3e\u65f6\u95f4:\n\u5176\u4ed6:[\u5982\u5305\u62ec\u8d60\u9001\u591a\u5c11IP]', max_length=255, verbose_name='\u5907\u6ce8')),
                ('bparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bparty', to='cmdb.Provider', verbose_name='\u4e59\u65b9')),
            ],
            options={
                'verbose_name': '/Meta/\u5408\u540c',
                'verbose_name_plural': '/Meta/\u5408\u540c',
            },
        ),
        migrations.CreateModel(
            name='ContractConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField(choices=[('1.1', '\u670d\u52a1\u5668\u7c7b\u9879\u76ee:\n\u7c7b\u522b:\n\u914d\u7f6e\u8be6\u60c5:\n\u6570\u91cf:\n\u54c1\u724c/\u89c4\u683c:\n\u5355\u4ef7:\n\u603b\u4ef7:\n'), ('2.1', '\u901a\u4fe1/\u901a\u8bdd\u7c7b\u9879\u76ee:\n\u7c7b\u522b:\n\u914d\u7f6e\u8be6\u60c5:\n\u6570\u91cf:\n\u54c1\u724c/\u89c4\u683c:\n\u5355\u4ef7:\n\u603b\u4ef7:\n'), ('3.1', '\u7f51\u7edc/\u5e26\u5bbd:\n\u7c7b\u522b:\n\u914d\u7f6e\u8be6\u60c5:\n\u6570\u91cf:\n\u54c1\u724c/\u89c4\u683c:\n\u5355\u4ef7:\n\u603b\u4ef7:\n')], max_length=255, verbose_name='\u72b6\u6001')),
                ('cost', models.TextField(choices=[('1.1', '\u670d\u52a1\u5668\u7c7b\u9879\u76ee:\n\u7c7b\u522b:\n\u914d\u7f6e\u8be6\u60c5:\n\u6570\u91cf:\n\u54c1\u724c/\u89c4\u683c:\n\u5355\u4ef7:\n\u603b\u4ef7:\n'), ('2.1', '\u901a\u4fe1/\u901a\u8bdd\u7c7b\u9879\u76ee:\n\u521d\u88c5\u8d39:\n\u6708\u56fa\u5b9a\u8d39\u7528:\n\u957f\u9014\u8d39\u7528:\n\u56fd\u9645\u8d39\u7528:\n\u5e02\u8bdd\u8d39\u7528/\u5206\u949f:\n\u957f\u9014\u8d39\u7528/\u5206\u949f:\n\u603b\u4ef7:\n\u4f18\u60e0\u4ef7/\u4f18\u60e0\u65b9\u5f0f:'), ('3.1', '\u7f51\u7edc/\u5e26\u5bbd:\n\u521d\u88c5\u8d39:\n\u6bcf\u6708\u56fa\u5b9a\u8d39\u7528:\n\u4f18\u60e0\u4ef7/\u4f18\u60e0\u65b9\u5f0f:')], default='6', max_length=255, verbose_name='\u72b6\u6001')),
                ('status', models.CharField(choices=[('1.1', '\u8be2\u4ef7'), ('2.1', '\u6bd4\u4ef7')], max_length=255, verbose_name='\u72b6\u6001')),
                ('stage', models.CharField(choices=[('1.1', '\u9996\u6b21'), ('2.1', '\u8c03\u6574')], max_length=255, verbose_name='\u9636\u6bb5')),
                ('op_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u53d8\u66f4\u65f6\u95f4')),
                ('prartyype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prartyype', to='cmdb.PrartType', verbose_name='\u914d\u7f6e\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '/Meta/\u5408\u540c\u8be6\u60c5[\u914d\u7f6e|\u94b1\u6b3e]',
                'verbose_name_plural': '/Meta/\u5408\u540c\u8be6\u60c5[\u914d\u7f6e|\u94b1\u6b3e]',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='conf_details',
            field=models.ManyToManyField(related_name='contractconfig', to='cmdb.ContractConfig', verbose_name='\u914d\u7f6e\u8be6\u60c5'),
        ),
    ]
