# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0086_recover_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID'),
        ),
        migrations.AlterField(
            model_name='recover',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID'),
        ),
    ]
