# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0087_auto_20161208_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='support_url',
            field=models.URLField(default='', max_length=255, verbose_name='\u6280\u672f\u652f\u6301\u5730\u5740'),
        ),
    ]
