# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0088_brandmodel_support_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='dept_ownerid',
            new_name='ownerid',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='dept_owneremail',
            new_name='ownermail',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='dept_ownername',
            new_name='ownername',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='dept_status',
            new_name='status',
        ),
    ]
