# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0089_auto_20161212_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPTTProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '\u6b63\u5e38'), ('2', '\u5f02\u5e38')], default='1', max_length=255, verbose_name='\u72b6\u6001')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u4ea7\u54c1\u7ebf')),
                ('memo', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmdb.MPTTProduct')),
            ],
            options={
                'verbose_name': '/Meta/\u4ea7\u54c1\u7ebf&\u4ea7\u54c1',
                'verbose_name_plural': '/Meta/\u4ea7\u54c1\u7ebf&\u4ea7\u54c1',
            },
        ),
    ]
