# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0090_mpttproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttproduct',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u4ea7\u54c1'),
        ),
        migrations.AlterField(
            model_name='mpttproduct',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmdb.MPTTProduct'),
        ),
    ]
